// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: user.proto

package server

import (
	"context"

	"github.com/lance977/hmms-zero/rpc/user/internal/logic"
	"github.com/lance977/hmms-zero/rpc/user/internal/svc"
	"github.com/lance977/hmms-zero/rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// ping
func (s *UserServer) Ping(ctx context.Context, in *user.PingReq) (*user.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// rpc SignIn(SignInReq) returns(SignInResp);
func (s *UserServer) SingInByAccount(ctx context.Context, in *user.SignInByAccountReq) (*user.SignInResp, error) {
	l := logic.NewSingInByAccountLogic(ctx, s.svcCtx)
	return l.SingInByAccount(in)
}

// 通过手机号登录
func (s *UserServer) SignInByPhone(ctx context.Context, in *user.SignInByPhoneReq) (*user.SignInResp, error) {
	l := logic.NewSignInByPhoneLogic(ctx, s.svcCtx)
	return l.SignInByPhone(in)
}
