// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: inventory.proto

package inventoryclient

import (
	"context"

	"github.com/lance977/hmms-zero/rpc/inventory/inventory"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = inventory.Request
	Response = inventory.Response

	Inventory interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultInventory struct {
		cli zrpc.Client
	}
)

func NewInventory(cli zrpc.Client) Inventory {
	return &defaultInventory{
		cli: cli,
	}
}

func (m *defaultInventory) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := inventory.NewInventoryClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
