// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: inventory.proto

package server

import (
	"context"

	"github.com/lance977/hmms-zero/rpc/inventory/internal/logic"
	"github.com/lance977/hmms-zero/rpc/inventory/internal/svc"
	"github.com/lance977/hmms-zero/rpc/inventory/inventory"
)

type InventoryServer struct {
	svcCtx *svc.ServiceContext
	inventory.UnimplementedInventoryServer
}

func NewInventoryServer(svcCtx *svc.ServiceContext) *InventoryServer {
	return &InventoryServer{
		svcCtx: svcCtx,
	}
}

func (s *InventoryServer) Ping(ctx context.Context, in *inventory.Request) (*inventory.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
