// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: home.proto

package server

import (
	"context"

	"github.com/lance977/hmms-zero/rpc/home/home"
	"github.com/lance977/hmms-zero/rpc/home/internal/logic"
	"github.com/lance977/hmms-zero/rpc/home/internal/svc"
)

type HomeServer struct {
	svcCtx *svc.ServiceContext
	home.UnimplementedHomeServer
}

func NewHomeServer(svcCtx *svc.ServiceContext) *HomeServer {
	return &HomeServer{
		svcCtx: svcCtx,
	}
}

func (s *HomeServer) Ping(ctx context.Context, in *home.PingReq) (*home.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
